RegisterNetEvent('cc_environment:time-day', function()
    NetworkOverrideClockTime(15, 0, 0)
end)
RegisterNetEvent('cc_environment:time-night', function()
    NetworkOverrideClockTime(0, 0, 0)
end)
RegisterNetEvent('cc_environment:time-morning', function()
    NetworkOverrideClockTime(7, 0, 0)
end)
RegisterNetEvent('cc_environment:time-evening', function()
    NetworkOverrideClockTime(20, 0, 0)
end)
RegisterNetEvent('cc_environment:time-noon', function()
    NetworkOverrideClockTime(12, 0, 0)
end)
RegisterNetEvent('cc_environment:weather-clear', function()
    SetOverrideWeather('CLEAR')
end)
RegisterNetEvent('cc_environment:weather-extrasunny', function()
    SetOverrideWeather('EXTRASUNNY')
end)
RegisterNetEvent('cc_environment:weather-cloudy', function()
    SetOverrideWeather('CLOUDS')
end)
RegisterNetEvent('cc_environment:weather-overcast', function()
    SetOverrideWeather('OVERCAST')
end)
RegisterNetEvent('cc_environment:weather-rain', function()
    SetOverrideWeather('RAIN')
end)
RegisterNetEvent('cc_environment:weather-clearing', function()
    SetOverrideWeather('CLEARING')
end)
RegisterNetEvent('cc_environment:weather-thunderstorm', function()
    SetOverrideWeather('THUNDER')
end)
RegisterNetEvent('cc_environment:weather-smog', function()
    SetOverrideWeather('SMOG')
end)
RegisterNetEvent('cc_environment:weather-foggy', function()
    SetOverrideWeather('FOGGY')
end)
RegisterNetEvent('cc_environment:weather-xmas', function()
    SetOverrideWeather('XMAS')
end)
RegisterNetEvent('cc_environment:weather-snow', function()
    SetOverrideWeather('SNOW')
end)
RegisterNetEvent('cc_environment:weather-snowlight', function()
    SetOverrideWeather('SNOWLIGHT')
end)
RegisterNetEvent('cc_environment:weather-blizzard', function()
    SetOverrideWeather('BLIZZARD')
end)
RegisterNetEvent('cc_environment:weather-halloween', function()
    SetOverrideWeather('HALLOWEEN')
end)
RegisterNetEvent('cc_environment:weather-neutral', function()
    SetOverrideWeather('NEUTRAL')
end)
